### ISSUE TITLE
memory leak in System::select()

### ISSUE THREAD

**Issue by mdimura** [yesint/pteros#20] opened 2020-04-30 17:13 UTC
This program leaks RAM proportionally to N (~20MB/1000 iterations):
```
#include "pteros/pteros.h"
#include "pteros/core/pteros_error.h"
#include <iostream>

using namespace pteros;

int main(int argc, char** argv){
    set_log_level("err");
    int N;
    std::cin>>N;
    System sys("small.gro");
    int seleSize=-1;
    for(int i=0; i<N; ++i) {
        auto sele = sys.select("chain A and resid 123 and not name CA CB C N O and chain B");
        seleSize = sele.size();
    }
    std::cout<<seleSize<<std::endl;
    return 0;
}

```
With more complex selection expressions it leaks more. This also seems to happen with valid selections.

> $ /usr/bin/time -v ./pteros_test_dcd <<< 2000 2>&1 | grep Maximum
>         Maximum resident set size (kbytes): 65324

**Comment by yesint** [comment] 2020-05-07 08:14
Could you try to localize the leak on your system?

**Comment by mdimura** [comment] 2020-05-07 08:24
It was not obvious to me. I tried to use gperftools for this, but I don't know the parser code well enough. Might be, that `peglib.h` is to blame.

**Comment by yesint** [comment] 2020-05-07 08:53
Please send me your small.gro file and a selection which causes the most pronounced leak. I can't reproduce it on my system so far, valgrind finds zero memory leaks.

**Comment by mdimura** [comment] 2020-05-07 09:46
[small.gro](https://github.com/yesint/pteros/blob/master/template/small.gro) is from the template. You can check, if the leak is there on your system by changing the N and comparing memory usage with, e.g. N=1000 vs N=2000. Memory usage should be the same, but on my system, it's not:
```
$ /usr/bin/time -v ./pteros_test_leak <<< 1000 2>&1 | grep 'Maximum resident'
        Maximum resident set size (kbytes): 56672
$ /usr/bin/time -v ./pteros_test_leak <<< 2000 2>&1 | grep 'Maximum resident'
        Maximum resident set size (kbytes): 69400
$ /usr/bin/time -v ./pteros_test_leak <<< 3000 2>&1 | grep 'Maximum resident'
        Maximum resident set size (kbytes): 86996
```
Here is the result of gperftools heap profiler:
![pprof_pteros-heap](https://user-images.githubusercontent.com/12734546/81284456-6a1f8e80-905e-11ea-8543-52e55f703b30.png)

**Comment by yesint** [comment] 2020-05-07 10:02
Ok, the leak is in peglib and it seems to be fixed in the new version. However the newest version of peglib doesn't compile with cryptic error messages. I'm not very good in CPP templates to understand what's wrong. I wrote to peglib developers.

**Comment by yesint** [comment] 2020-05-07 10:04
Here is the bug report https://github.com/yhirose/cpp-peglib/issues/102
You may try to pull the latest peglib.h and look at the error, may be you'll grasp what's wrong.

**Comment by mdimura** [comment] 2020-05-07 10:11
I tried the new peglib too, had the same issue with errors.

**Comment by mdimura** [comment] 2020-05-07 11:01
I think I found a workaround. It is probably a good idea to update peglib from upstream anyway, but this can patch the leak until then.

**Comment by yesint** [comment] 2020-05-07 11:28
I'll leave it open in order not to forget to use new peglib when compilation issue is solved upstream.

**Comment by yesint** [comment] 2020-05-23 16:30
New peglib is integrated. Closing.

**Closed as completed by yesint** 2020-05-23 16:30 UTC
